"""
Synthetic e-commerce sales data generator.

Produces a single flat dataset (one row per order) matching the project's
column spec, with realistic structure baked in rather than pure randomness:

- Revenue grows ~35% from the start to the end of the window, with a
  Nov/Dec holiday seasonal bump and a smaller August back-to-school bump.
- The South and West regions carry the largest share of order volume.
- Electronics carries the thinnest margins of any category, so heavily
  discounted electronics orders occasionally post a loss - a real pattern
  worth surfacing later in the "business insights" feature.
- A minority of customers order repeatedly (order counts are drawn from a
  skewed log-normal distribution, not sampled uniformly), so repeat-customer
  and CLV analysis in later phases has something real to find.

No third-party dependency beyond pandas/numpy: customer and product names
are generated by combining small hand-written word pools rather than
pulling in Faker, since it isn't needed at runtime and this keeps data
generation dependency-free.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd

from utils.logger import get_logger

logger = get_logger(__name__)

# --------------------------------------------------------------------------
# Reference data: US regions -> states -> cities.
# --------------------------------------------------------------------------
REGION_STATE_CITIES: dict[str, dict[str, list[str]]] = {
    "Northeast": {
        "New York": ["New York City", "Buffalo"],
        "Massachusetts": ["Boston", "Worcester"],
        "Pennsylvania": ["Philadelphia", "Pittsburgh"],
        "New Jersey": ["Newark", "Jersey City"],
    },
    "Midwest": {
        "Illinois": ["Chicago", "Springfield"],
        "Ohio": ["Columbus", "Cleveland"],
        "Michigan": ["Detroit", "Grand Rapids"],
        "Minnesota": ["Minneapolis", "St. Paul"],
        "Missouri": ["Kansas City", "St. Louis"],
    },
    "South": {
        "Texas": ["Houston", "Dallas", "Austin", "San Antonio"],
        "Florida": ["Miami", "Orlando", "Tampa"],
        "Georgia": ["Atlanta", "Savannah"],
        "North Carolina": ["Charlotte", "Raleigh"],
        "Virginia": ["Richmond", "Norfolk"],
    },
    "West": {
        "California": ["Los Angeles", "San Francisco", "San Diego", "Sacramento"],
        "Washington": ["Seattle", "Spokane"],
        "Arizona": ["Phoenix", "Tucson"],
        "Colorado": ["Denver", "Boulder"],
        "Nevada": ["Las Vegas", "Reno"],
    },
}

# Relative order-volume weight per region - South and West lead, by design.
REGION_WEIGHTS = {"South": 0.38, "West": 0.27, "Northeast": 0.19, "Midwest": 0.16}

COUNTRY = "United States"


@dataclass(frozen=True)
class CategorySpec:
    """Everything needed to generate one product category's catalog and orders."""

    name: str
    sub_categories: tuple[str, ...]
    price_range: tuple[float, float]
    cost_ratio_range: tuple[float, float]
    order_weight: float
    return_rate_bump: float


CATEGORY_SPECS: tuple[CategorySpec, ...] = (
    CategorySpec(
        "Electronics",
        ("Smartphones", "Laptops", "Headphones", "Tablets", "Accessories"),
        (25.0, 1200.0), (0.68, 0.82), 0.26, 0.02,
    ),
    CategorySpec(
        "Clothing",
        ("Men's Apparel", "Women's Apparel", "Kids' Apparel", "Footwear"),
        (15.0, 150.0), (0.40, 0.55), 0.24, 0.07,
    ),
    CategorySpec(
        "Home & Kitchen",
        ("Furniture", "Cookware", "Decor", "Appliances"),
        (20.0, 800.0), (0.45, 0.60), 0.18, 0.02,
    ),
    CategorySpec(
        "Sports & Outdoors",
        ("Fitness Equipment", "Camping Gear", "Cycling", "Team Sports"),
        (15.0, 500.0), (0.42, 0.58), 0.14, 0.02,
    ),
    CategorySpec(
        "Beauty & Personal Care",
        ("Skincare", "Haircare", "Makeup", "Fragrance"),
        (8.0, 120.0), (0.25, 0.40), 0.12, 0.03,
    ),
    CategorySpec(
        "Books & Media",
        ("Fiction", "Non-Fiction", "Educational", "Digital Media"),
        (6.0, 45.0), (0.55, 0.70), 0.06, 0.01,
    ),
)

# Singular noun used when building a product name for each sub-category.
SUBCATEGORY_NOUNS: dict[str, str] = {
    "Smartphones": "Smartphone", "Laptops": "Laptop", "Headphones": "Headphones",
    "Tablets": "Tablet", "Accessories": "Accessory",
    "Men's Apparel": "Shirt", "Women's Apparel": "Dress", "Kids' Apparel": "Outfit",
    "Footwear": "Sneaker",
    "Furniture": "Chair", "Cookware": "Pan", "Decor": "Vase", "Appliances": "Blender",
    "Fitness Equipment": "Dumbbell", "Camping Gear": "Tent", "Cycling": "Bike",
    "Team Sports": "Jersey",
    "Skincare": "Moisturizer", "Haircare": "Shampoo", "Makeup": "Palette",
    "Fragrance": "Perfume",
    "Fiction": "Novel", "Non-Fiction": "Book", "Educational": "Workbook",
    "Digital Media": "Audiobook",
}

PRODUCT_ADJECTIVES = [
    "Nova", "Ridge", "Ember", "Vertex", "Aria", "Summit", "Lumen", "Atlas", "Ion", "Crest",
    "Haven", "Cove", "Drift", "Pulse", "Echo", "Fable", "Grove", "Hollow", "Juno", "Kite",
]
PRODUCT_SUFFIXES = ["", "", " Pro", " Elite", " Plus", " Lite", " X2", " Mark II", " 360", " Max"]

SALES_CHANNELS = {"Online": 0.48, "Mobile App": 0.27, "In-Store": 0.17, "Marketplace": 0.08}
PAYMENT_METHODS = {"Credit Card": 0.44, "Debit Card": 0.26, "PayPal": 0.18, "Gift Card": 0.07, "Cash": 0.05}

FIRST_NAMES = [
    "James", "Mary", "Robert", "Patricia", "John", "Jennifer", "Michael", "Linda", "David", "Elizabeth",
    "William", "Barbara", "Richard", "Susan", "Joseph", "Jessica", "Thomas", "Sarah", "Charles", "Karen",
    "Christopher", "Nancy", "Daniel", "Lisa", "Matthew", "Betty", "Anthony", "Margaret", "Mark", "Sandra",
    "Donald", "Ashley", "Steven", "Kimberly", "Andrew", "Emily", "Joshua", "Donna", "Kenneth", "Michelle",
    "Priya", "Wei", "Fatima", "Diego", "Aiko", "Omar", "Ingrid", "Sofia", "Liam", "Noah",
]
LAST_NAMES = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez",
    "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin",
    "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson",
    "Walker", "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores",
]

PRODUCTS_PER_SUBCATEGORY = 6


def _generate_customers(n_customers: int, rng: np.random.Generator) -> pd.DataFrame:
    """Build the customer lookup pool with a skewed per-customer order weight."""
    regions = list(REGION_WEIGHTS.keys())
    region_p = list(REGION_WEIGHTS.values())
    chosen_regions = rng.choice(regions, size=n_customers, p=region_p)

    states, cities = [], []
    for region in chosen_regions:
        state = rng.choice(list(REGION_STATE_CITIES[region].keys()))
        city = rng.choice(REGION_STATE_CITIES[region][state])
        states.append(state)
        cities.append(city)

    first = rng.choice(FIRST_NAMES, size=n_customers)
    last = rng.choice(LAST_NAMES, size=n_customers)
    names = [f"{f} {l}" for f, l in zip(first, last)]

    return pd.DataFrame({
        "Customer_ID": [f"CUST{i:05d}" for i in range(1, n_customers + 1)],
        "Customer_Name": names,
        "Age": rng.integers(18, 76, size=n_customers),
        "Gender": rng.choice(["Female", "Male", "Other"], size=n_customers, p=[0.49, 0.47, 0.04]),
        "City": cities,
        "State": states,
        "Region": chosen_regions,
        "Country": COUNTRY,
        # Internal only: log-normal order propensity so a minority of
        # customers place most of the repeat orders. Dropped before export.
        "_order_weight": rng.lognormal(mean=0.0, sigma=0.9, size=n_customers),
    })


def _generate_products(rng: np.random.Generator) -> pd.DataFrame:
    """Build the product catalog: a fixed number of SKUs per sub-category."""
    rows = []
    product_num = 1
    for spec in CATEGORY_SPECS:
        for sub in spec.sub_categories:
            noun = SUBCATEGORY_NOUNS[sub]
            for _ in range(PRODUCTS_PER_SUBCATEGORY):
                name = f"{rng.choice(PRODUCT_ADJECTIVES)} {noun}{rng.choice(PRODUCT_SUFFIXES)}".strip()
                price = round(float(rng.uniform(*spec.price_range)), 2)
                cost_ratio = float(rng.uniform(*spec.cost_ratio_range))
                rows.append({
                    "Product_ID": f"PRD{product_num:04d}",
                    "Category": spec.name,
                    "Sub_Category": sub,
                    "Product_Name": name,
                    "Unit_Price": price,
                    "Cost": round(price * cost_ratio, 2),
                    # Internal only: dropped before export.
                    "_category_weight": spec.order_weight,
                    "_return_bump": spec.return_rate_bump,
                })
                product_num += 1
    return pd.DataFrame(rows)


def _generate_orders(
    n_orders: int,
    customers: pd.DataFrame,
    products: pd.DataFrame,
    start_date: date,
    end_date: date,
    rng: np.random.Generator,
) -> pd.DataFrame:
    """Sample `n_orders` transactions across the customer and product pools."""
    calendar = pd.date_range(start=start_date, end=end_date, freq="D")
    total_days = len(calendar) - 1

    day_offsets = np.arange(len(calendar))
    growth = 1.0 + 0.35 * (day_offsets / total_days)
    month_of = calendar.month.to_numpy()
    seasonal = np.where(np.isin(month_of, [11, 12]), 1.6, 1.0)
    seasonal = np.where(month_of == 8, seasonal * 1.15, seasonal)
    weekend_bump = np.where(calendar.weekday.to_numpy() >= 5, 1.2, 1.0)
    day_weights = growth * seasonal * weekend_bump
    day_weights = day_weights / day_weights.sum()

    order_dates = calendar[rng.choice(len(calendar), size=n_orders, p=day_weights)]

    cust_p = customers["_order_weight"].to_numpy()
    cust_rows = customers.iloc[rng.choice(len(customers), size=n_orders, p=cust_p / cust_p.sum())]
    cust_rows = cust_rows.reset_index(drop=True)

    prod_p = products["_category_weight"].to_numpy()
    prod_rows = products.iloc[rng.choice(len(products), size=n_orders, p=prod_p / prod_p.sum())]
    prod_rows = prod_rows.reset_index(drop=True)

    quantities = rng.choice(
        [1, 2, 3, 4, 5, 6, 8, 10], size=n_orders,
        p=[0.34, 0.24, 0.16, 0.10, 0.07, 0.04, 0.03, 0.02],
    )

    is_promo = rng.random(n_orders) < 0.12
    discounts = np.round(
        np.where(is_promo, rng.uniform(0.25, 0.45, n_orders), rng.uniform(0.0, 0.15, n_orders)), 2
    )

    ship_lag_days = rng.choice(
        [1, 2, 3, 4, 5, 7, 10], size=n_orders, p=[0.22, 0.28, 0.22, 0.13, 0.08, 0.05, 0.02]
    )
    ship_dates = order_dates + pd.to_timedelta(ship_lag_days, unit="D")

    unit_prices = prod_rows["Unit_Price"].to_numpy()
    unit_costs = prod_rows["Cost"].to_numpy()
    revenue = np.round(quantities * unit_prices * (1 - discounts), 2)
    profit = np.round(revenue - quantities * unit_costs, 2)

    channels = rng.choice(list(SALES_CHANNELS), size=n_orders, p=list(SALES_CHANNELS.values()))
    payments = rng.choice(list(PAYMENT_METHODS), size=n_orders, p=list(PAYMENT_METHODS.values()))

    base_return_p = 0.05
    return_p = base_return_p + prod_rows["_return_bump"].to_numpy() + np.where(is_promo, 0.05, 0.0)
    returned = rng.random(n_orders) < return_p

    rating = np.clip(np.round(rng.normal(4.25, 0.85, n_orders)), 1, 5).astype(int)
    rating = np.where(returned, np.clip(rating - rng.integers(1, 3, n_orders), 1, 5), rating)

    orders = pd.DataFrame({
        "Order_ID": [f"ORD{i:06d}" for i in range(1, n_orders + 1)],
        "Order_Date": pd.DatetimeIndex(order_dates),
        "Ship_Date": pd.DatetimeIndex(ship_dates),
        "Customer_ID": cust_rows["Customer_ID"].to_numpy(),
        "Customer_Name": cust_rows["Customer_Name"].to_numpy(),
        "Age": cust_rows["Age"].to_numpy(),
        "Gender": cust_rows["Gender"].to_numpy(),
        "City": cust_rows["City"].to_numpy(),
        "State": cust_rows["State"].to_numpy(),
        "Region": cust_rows["Region"].to_numpy(),
        "Country": cust_rows["Country"].to_numpy(),
        "Product_ID": prod_rows["Product_ID"].to_numpy(),
        "Category": prod_rows["Category"].to_numpy(),
        "Sub_Category": prod_rows["Sub_Category"].to_numpy(),
        "Product_Name": prod_rows["Product_Name"].to_numpy(),
        "Quantity": quantities,
        "Unit_Price": unit_prices,
        "Discount": discounts,  # fraction, e.g. 0.20 == 20% off
        "Cost": unit_costs,
        "Revenue": revenue,
        "Profit": profit,
        "Sales_Channel": channels,
        "Payment_Method": payments,
        "Returned": np.where(returned, "Yes", "No"),
        "Delivery_Time": ship_lag_days,  # days between Order_Date and Ship_Date
        "Rating": rating,
    })

    return orders.sort_values("Order_Date").reset_index(drop=True)


def generate_dataset(
    n_orders: int = 100_000,
    n_customers: int = 6_000,
    start_date: date = date(2024, 7, 1),
    end_date: date = date(2026, 6, 30),
    seed: int = 42,
) -> pd.DataFrame:
    """Generate a synthetic flat sales dataset with `n_orders` rows.

    Deterministic for a given `seed`. Each row denormalizes customer and
    product attributes onto the order - matching what a BI export from a
    real e-commerce warehouse typically looks like. `database/` re-normalizes
    this back into customers/products/orders tables in Phase 3.
    """
    rng = np.random.default_rng(seed)
    logger.info("Generating %d customers", n_customers)
    customers = _generate_customers(n_customers, rng)
    logger.info("Generating product catalog")
    products = _generate_products(rng)
    logger.info("Generating %d orders", n_orders)
    orders = _generate_orders(n_orders, customers, products, start_date, end_date, rng)
    logger.info("Dataset generated: %d rows, %d columns", *orders.shape)
    return orders


def save_dataset(df: pd.DataFrame, path: Path) -> None:
    """Write the dataset to CSV, creating parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    logger.info("Saved dataset to %s (%.1f MB)", path, path.stat().st_size / 1e6)


if __name__ == "__main__":
    from utils.config import settings

    dataset = generate_dataset()
    save_dataset(dataset, settings.data_raw_dir / "sales_data.csv")
    logger.info("Preview:\n%s", dataset.head(3).to_string())
